# Generated by Django 3.0.4 on 2020-04-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='is_active',
        ),
    ]
