default:
        SECRET_KEY: ""
        DEBUG: true
        ALLOWED HOSTS: []
        DATABASE_URL: "postgresql://postgres:afx432k94003755@localhost:5432/nazrep"

development:
        DEBUG: true
        ALLOWED_HOSTS:
                - 127.0.0.1
                - localhost

heroku:
        DEBUG: false
        ALLOWED_HOSTS:
                - 127.0.0.1
                - localhost
                - nazhello.herokuapp.com

travis:
        DEBUG: true
        ALLOWED_HOSTS:
                - 127.0.0.1
                - localhost
        DATABASE_URL: "postgresql://postgres:afx432k94003755@localhost:5432/nazrep"
        SECRET_KEY: "xxx"
